// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "swapi-ts",
    "version": "1"
  },
  "paths": {
    "/api/health": {
      "get": {
        "summary": "health",
        "description": "",
        "operationId": "health.get./api/health",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/people": {
      "get": {
        "summary": "listPeople",
        "description": "",
        "operationId": "listPeople.get./api/people",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/planets": {
      "get": {
        "summary": "listPlanets",
        "description": "",
        "operationId": "listPlanets.get./api/planets",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/vehicles": {
      "post": {
        "summary": "createVehicle",
        "description": "",
        "operationId": "createVehicle.post./api/vehicles",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/vehicles/{vehicle_id}": {
      "get": {
        "summary": "getVehicle",
        "description": "",
        "operationId": "getVehicle.get./api/vehicles/{vehicle_id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vehicle_id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Vehicle": {
      "properties": {
        "cargo_capacity": {
          "title": "Vehicle.cargo_capacity",
          "type": "string"
        },
        "consumables": {
          "title": "Vehicle.consumables",
          "type": "string"
        },
        "cost_in_credits": {
          "title": "Vehicle.cost_in_credits",
          "type": "string"
        },
        "created": {
          "title": "Vehicle.created",
          "type": "string"
        },
        "crew": {
          "title": "Vehicle.crew",
          "type": "string"
        },
        "edited": {
          "title": "Vehicle.edited",
          "type": "string"
        },
        "length": {
          "title": "Vehicle.length",
          "type": "string"
        },
        "manufacturer": {
          "title": "Vehicle.manufacturer",
          "type": "string"
        },
        "max_atmosphering_speed": {
          "title": "Vehicle.max_atmosphering_speed",
          "type": "string"
        },
        "model": {
          "title": "Vehicle.model",
          "type": "string"
        },
        "name": {
          "title": "Vehicle.name",
          "type": "string"
        },
        "passengers": {
          "title": "Vehicle.passengers",
          "type": "string"
        },
        "pilots": {
          "items": {
            "title": "Vehicle.pilots.[]",
            "type": "string"
          },
          "title": "Vehicle.pilots",
          "type": "array"
        },
        "films": {
          "items": {
            "$ref": "#/definitions/Films",
            "title": "Vehicle.films.[]"
          },
          "title": "Vehicle.films",
          "type": "array"
        },
        "url": {
          "title": "Vehicle.url",
          "type": "string"
        },
        "vehicle_class": {
          "title": "Vehicle.vehicle_class",
          "type": "string"
        }
      },
      "required": [
        "cargo_capacity",
        "consumables",
        "cost_in_credits",
        "created",
        "crew",
        "edited",
        "length",
        "manufacturer",
        "max_atmosphering_speed",
        "model",
        "name",
        "passengers",
        "pilots",
        "films",
        "url",
        "vehicle_class"
      ],
      "additionalProperties": false,
      "title": "Vehicle",
      "type": "object"
    },
    "Films": {
      "properties": {
        "starships": {
          "items": {
            "title": "Films.starships.[]",
            "type": "string"
          },
          "title": "Films.starships",
          "type": "array"
        },
        "edited": {
          "title": "Films.edited",
          "type": "string"
        },
        "planets": {
          "items": {
            "title": "Films.planets.[]",
            "type": "string"
          },
          "title": "Films.planets",
          "type": "array"
        },
        "producer": {
          "title": "Films.producer",
          "type": "string"
        },
        "title": {
          "title": "Films.title",
          "type": "string"
        },
        "url": {
          "title": "Films.url",
          "type": "string"
        },
        "release_date": {
          "title": "Films.release_date",
          "type": "string"
        },
        "vehicles": {
          "items": {
            "$ref": "#/definitions/Vehicle",
            "title": "Films.vehicles.[]"
          },
          "title": "Films.vehicles",
          "type": "array"
        },
        "episode_id": {
          "title": "Films.episode_id",
          "type": "number"
        },
        "director": {
          "title": "Films.director",
          "type": "string"
        },
        "created": {
          "title": "Films.created",
          "type": "string"
        },
        "opening_crawl": {
          "title": "Films.opening_crawl",
          "type": "string"
        },
        "characters": {
          "items": {
            "title": "Films.characters.[]",
            "type": "string"
          },
          "title": "Films.characters",
          "type": "array"
        },
        "species": {
          "items": {
            "title": "Films.species.[]",
            "type": "string"
          },
          "title": "Films.species",
          "type": "array"
        }
      },
      "required": [
        "starships",
        "edited",
        "planets",
        "producer",
        "title",
        "url",
        "release_date",
        "vehicles",
        "episode_id",
        "director",
        "created",
        "opening_crawl",
        "characters",
        "species"
      ],
      "additionalProperties": false,
      "title": "Films",
      "type": "object"
    },
    "Person": {
      "properties": {
        "starships": {
          "items": {
            "title": "Person.starships.[]",
            "type": "string"
          },
          "title": "Person.starships",
          "type": "array"
        },
        "edited": {
          "title": "Person.edited",
          "type": "string"
        },
        "name": {
          "title": "Person.name",
          "type": "string"
        },
        "created": {
          "title": "Person.created",
          "type": "string"
        },
        "url": {
          "title": "Person.url",
          "type": "string"
        },
        "gender": {
          "title": "Person.gender",
          "type": "string"
        },
        "vehicles": {
          "items": {
            "title": "Person.vehicles.[]",
            "type": "string"
          },
          "title": "Person.vehicles",
          "type": "array"
        },
        "skin_color": {
          "title": "Person.skin_color",
          "type": "string"
        },
        "hair_color": {
          "title": "Person.hair_color",
          "type": "string"
        },
        "height": {
          "title": "Person.height",
          "type": "string"
        },
        "eye_color": {
          "title": "Person.eye_color",
          "type": "string"
        },
        "mass": {
          "title": "Person.mass",
          "type": "string"
        },
        "films": {
          "items": {
            "title": "Person.films.[]",
            "type": "string"
          },
          "title": "Person.films",
          "type": "array"
        },
        "species": {
          "items": {
            "title": "Person.species.[]",
            "type": "string"
          },
          "title": "Person.species",
          "type": "array"
        },
        "homeworld": {
          "title": "Person.homeworld",
          "type": "string"
        },
        "birth_year": {
          "title": "Person.birth_year",
          "type": "string"
        }
      },
      "required": [
        "starships",
        "edited",
        "name",
        "created",
        "url",
        "gender",
        "vehicles",
        "skin_color",
        "hair_color",
        "height",
        "eye_color",
        "mass",
        "films",
        "species",
        "homeworld",
        "birth_year"
      ],
      "additionalProperties": false,
      "title": "Person",
      "type": "object"
    },
    "ListPeople": {
      "properties": {
        "data": {
          "$ref": "#/definitions/People",
          "title": "ListPeople.data"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "ListPeople",
      "type": "object"
    },
    "People": {
      "properties": {
        "people": {
          "items": {
            "$ref": "#/definitions/Person",
            "title": "People.people.[]"
          },
          "title": "People.people",
          "type": "array"
        }
      },
      "required": [
        "people"
      ],
      "additionalProperties": false,
      "title": "People",
      "type": "object"
    },
    "Planet": {
      "properties": {
        "diameter": {
          "title": "Planet.diameter",
          "type": "string"
        },
        "climate": {
          "title": "Planet.climate",
          "type": "string"
        },
        "surface_water": {
          "title": "Planet.surface_water",
          "type": "string"
        },
        "name": {
          "title": "Planet.name",
          "type": "string"
        },
        "created": {
          "title": "Planet.created",
          "type": "string"
        },
        "url": {
          "title": "Planet.url",
          "type": "string"
        },
        "rotation_period": {
          "title": "Planet.rotation_period",
          "type": "string"
        },
        "edited": {
          "title": "Planet.edited",
          "type": "string"
        },
        "terrain": {
          "title": "Planet.terrain",
          "type": "string"
        },
        "gravity": {
          "title": "Planet.gravity",
          "type": "string"
        },
        "orbital_period": {
          "title": "Planet.orbital_period",
          "type": "string"
        },
        "films": {
          "items": {
            "title": "Planet.films.[]",
            "type": "string"
          },
          "title": "Planet.films",
          "type": "array"
        },
        "residents": {
          "items": {
            "title": "Planet.residents.[]",
            "type": "string"
          },
          "title": "Planet.residents",
          "type": "array"
        },
        "population": {
          "title": "Planet.population",
          "type": "string"
        }
      },
      "required": [
        "diameter",
        "climate",
        "surface_water",
        "name",
        "created",
        "url",
        "rotation_period",
        "edited",
        "terrain",
        "gravity",
        "orbital_period",
        "films",
        "residents",
        "population"
      ],
      "additionalProperties": false,
      "title": "Planet",
      "type": "object"
    },
    "ListPlanets": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Planets",
          "title": "ListPlanets.data"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "ListPlanets",
      "type": "object"
    },
    "Planets": {
      "properties": {
        "planets": {
          "items": {
            "$ref": "#/definitions/Planet",
            "title": "Planets.planets.[]"
          },
          "title": "Planets.planets",
          "type": "array"
        }
      },
      "required": [
        "planets"
      ],
      "additionalProperties": false,
      "title": "Planets",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};